<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FinanceProductSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed Finance Products
        $products = [
            [
                'code' => 'zero_cibil_daily',
                'name' => 'Interest-Free / Zero CIBIL Loan',
                'category' => 'zero_cibil',
                'min_amount' => 20000,
                'max_amount' => 200000,
                'min_tenure_months' => 3,
                'max_tenure_months' => 12,
                'interest_rate_p_a' => 0.00,
                'is_interest_free' => true,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 1999,
                'processing_fee_slabs' => json_encode([
                    ['amount' => 20000, 'fee' => 1500, 'daily_emi' => 500, 'daily_limit' => 2000],
                    ['amount' => 50000, 'fee' => 2500, 'daily_emi' => 1000, 'daily_limit' => 5000],
                    ['amount' => 100000, 'fee' => 3500, 'daily_emi' => 1000, 'daily_limit' => 5000],
                    ['amount' => 200000, 'fee' => 4999, 'daily_emi' => 2000, 'daily_limit' => 10000],
                ]),
                'daily_repayment_amount' => 1000,
                'daily_usage_limit' => 5000,
                'grace_period_days' => 1,
                'late_fee' => 100,
                'penalty_rate' => 2.00,
                'auto_verify' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cash_loan_low_cibil',
                'name' => 'Low CIBIL Cash Loan',
                'category' => 'cash_loan',
                'min_amount' => 50000,
                'max_amount' => 400000,
                'min_tenure_months' => 12,
                'max_tenure_months' => 48,
                'interest_rate_p_a' => 11.50,
                'is_interest_free' => false,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 2499,
                'processing_fee_slabs' => null,
                'daily_repayment_amount' => null,
                'daily_usage_limit' => null,
                'grace_period_days' => 3,
                'late_fee' => 250,
                'penalty_rate' => 2.50,
                'auto_verify' => false,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'cash_loan_good_cibil',
                'name' => 'Good CIBIL Cash Loan',
                'category' => 'cash_loan',
                'min_amount' => 200000,
                'max_amount' => 5000000,
                'min_tenure_months' => 12,
                'max_tenure_months' => 60,
                'interest_rate_p_a' => 9.50,
                'is_interest_free' => false,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 3999,
                'processing_fee_slabs' => null,
                'daily_repayment_amount' => null,
                'daily_usage_limit' => null,
                'grace_period_days' => 5,
                'late_fee' => 500,
                'penalty_rate' => 2.00,
                'auto_verify' => false,
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'virtual_loan',
                'name' => 'App-to-App Virtual Credit',
                'category' => 'virtual_loan',
                'min_amount' => 15000,
                'max_amount' => 45000,
                'min_tenure_months' => 1,
                'max_tenure_months' => 6,
                'interest_rate_p_a' => 0.00,
                'is_interest_free' => true,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 2000,
                'processing_fee_slabs' => json_encode([
                    ['amount' => 15000, 'fee' => 2000, 'daily_limit' => 3000, 'daily_repayment' => 500],
                    ['amount' => 20000, 'fee' => 3000, 'daily_limit' => 4000, 'daily_repayment' => 700],
                    ['amount' => 30000, 'fee' => 3000, 'daily_limit' => 5000, 'daily_repayment' => 1000],
                    ['amount' => 35000, 'fee' => 4000, 'daily_limit' => 6000, 'daily_repayment' => 1200],
                    ['amount' => 45000, 'fee' => 4000, 'daily_limit' => 8000, 'daily_repayment' => 1500],
                ]),
                'daily_repayment_amount' => 1000,
                'daily_usage_limit' => 5000,
                'grace_period_days' => 2,
                'late_fee' => 100,
                'penalty_rate' => 2.00,
                'auto_verify' => true,
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'business_loan',
                'name' => 'Business / Fleet Expansion Loan',
                'category' => 'business_loan',
                'min_amount' => 500000,
                'max_amount' => 20000000,
                'min_tenure_months' => 12,
                'max_tenure_months' => 84,
                'interest_rate_p_a' => 10.50,
                'is_interest_free' => false,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 5999,
                'processing_fee_slabs' => null,
                'daily_repayment_amount' => null,
                'daily_usage_limit' => null,
                'grace_period_days' => 7,
                'late_fee' => 1000,
                'penalty_rate' => 2.00,
                'auto_verify' => false,
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'student_credit_domestic',
                'name' => 'Student Credit (Domestic)',
                'category' => 'student_credit',
                'min_amount' => 10000,
                'max_amount' => 75000,
                'min_tenure_months' => 3,
                'max_tenure_months' => 24,
                'interest_rate_p_a' => 0.00,
                'is_interest_free' => true,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 999,
                'processing_fee_slabs' => null,
                'daily_repayment_amount' => null,
                'daily_usage_limit' => null,
                'grace_period_days' => 5,
                'late_fee' => 100,
                'penalty_rate' => 1.50,
                'auto_verify' => false,
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'student_credit_intl',
                'name' => 'Student Credit (International)',
                'category' => 'student_credit',
                'min_amount' => 50000,
                'max_amount' => 500000,
                'min_tenure_months' => 6,
                'max_tenure_months' => 36,
                'interest_rate_p_a' => 6.50,
                'is_interest_free' => false,
                'processing_fee_type' => 'fixed',
                'processing_fee_value' => 2999,
                'processing_fee_slabs' => null,
                'daily_repayment_amount' => null,
                'daily_usage_limit' => null,
                'grace_period_days' => 7,
                'late_fee' => 500,
                'penalty_rate' => 2.00,
                'auto_verify' => false,
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($products as $p) {
            DB::table('finance_loan_products')->updateOrInsert(['code' => $p['code']], $p);
        }

        // 2. Seed Lender Partners
        $partners = [
            [
                'name' => 'HDFC Bank',
                'logo' => 'https://upload.wikimedia.org/wikipedia/commons/2/28/HDFC_Bank_Logo.svg',
                'loan_types' => json_encode(['cash_loan', 'business_loan']),
                'min_loan_amount' => 100000,
                'max_loan_amount' => 5000000,
                'interest_rate_display' => '10.5% p.a.',
                'tenure_display' => '12 - 72 Months',
                'processing_fee_display' => 'Up to 1.5% of loan amount',
                'application_url' => 'https://www.hdfcbank.com/personal/borrow/popular-loans/personal-loan',
                'status' => 'active',
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ICICI Bank',
                'logo' => 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/ICICI_Bank_Logo.svg/1200px-ICICI_Bank_Logo.svg.png',
                'loan_types' => json_encode(['cash_loan', 'business_loan']),
                'min_loan_amount' => 100000,
                'max_loan_amount' => 5000000,
                'interest_rate_display' => '10.75% p.a.',
                'tenure_display' => '12 - 60 Months',
                'processing_fee_display' => 'As applicable',
                'application_url' => 'https://www.icicibank.com/personal-banking/loans/personal-loan',
                'status' => 'active',
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tata Capital',
                'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Tata_logo.svg/1200px-Tata_logo.svg.png',
                'loan_types' => json_encode(['cash_loan', 'business_loan']),
                'min_loan_amount' => 50000,
                'max_loan_amount' => 3500000,
                'interest_rate_display' => '11.25% p.a.',
                'tenure_display' => '12 - 84 Months',
                'processing_fee_display' => 'Zero to nominal',
                'application_url' => 'https://www.tatacapital.com/personal-loan.html',
                'status' => 'active',
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bajaj Finserv',
                'logo' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Bajaj_Finserv_Logo.svg/1200px-Bajaj_Finserv_Logo.svg.png',
                'loan_types' => json_encode(['cash_loan', 'business_loan']),
                'min_loan_amount' => 50000,
                'max_loan_amount' => 4000000,
                'interest_rate_display' => '11.5% p.a.',
                'tenure_display' => '12 - 60 Months',
                'processing_fee_display' => 'As applicable',
                'application_url' => 'https://www.bajajfinserv.in/personal-loan',
                'status' => 'active',
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($partners as $partner) {
            DB::table('finance_lender_partners')->updateOrInsert(['name' => $partner['name']], $partner);
        }
    }
}
