@extends('layouts.app')

@section('content')
<div class="page-wrapper">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor font-weight-bold">🤝 Referral Cost & Revenue</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url('/dashboard') }}">Home</a></li>
                <li class="breadcrumb-item">Earning Management</li>
                <li class="breadcrumb-item active">Referral Cost & Revenue</li>
            </ol>
        </div>
    </div>

    <div class="container-fluid">
        <!-- 4 Summary Cards -->
        <div class="row">
            <div class="col-md-3">
                <div class="card border rounded p-3 bg-light text-center">
                    <small class="text-muted font-weight-bold uppercase">Referral Generated Txns</small>
                    <h3 class="font-weight-bold mt-1 mb-0 text-primary">{{ number_format($referralSummary['referral_generated_txns']) }}</h3>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border rounded p-3 bg-light text-center">
                    <small class="text-muted font-weight-bold uppercase">Referral Rewards Paid</small>
                    <h3 class="font-weight-bold mt-1 mb-0 text-danger">₹{{ number_format($referralSummary['referral_rewards_paid']) }}</h3>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border rounded p-3 bg-light text-center">
                    <small class="text-muted font-weight-bold uppercase">Revenue by Referred Users</small>
                    <h3 class="font-weight-bold mt-1 mb-0 text-info">₹{{ number_format($referralSummary['revenue_by_referred_users']) }}</h3>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border rounded p-3 bg-success text-white text-center">
                    <small class="text-white-50 font-weight-bold uppercase">Net Referral Contribution</small>
                    <h3 class="font-weight-bold mt-1 mb-0">₹{{ number_format($referralSummary['net_referral_contribution']) }}</h3>
                </div>
            </div>
        </div>

        <div class="card shadow-sm border-0 rounded-lg mt-4">
            <div class="card-body">
                <h4 class="card-title font-weight-bold border-bottom pb-2">Referral Impact & ROI Metrics</h4>
                <p class="text-muted small">Comparison between cash rewards distributed to referrers versus revenue generated by new referred users.</p>

                <div class="row text-center mt-4">
                    <div class="col-md-4">
                        <div class="p-3 border rounded">
                            <h2 class="text-success font-weight-bold">13.2x</h2>
                            <p class="text-muted mb-0 font-weight-bold">Referral ROI Ratio</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="p-3 border rounded">
                            <h2 class="text-info font-weight-bold">₹14.18</h2>
                            <p class="text-muted mb-0 font-weight-bold">Cost Per Acquisition (CPA)</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="p-3 border rounded">
                            <h2 class="text-primary font-weight-bold">₹187.13</h2>
                            <p class="text-muted mb-0 font-weight-bold">Avg Revenue per Referred User</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
